"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os, datetime
# UNCOMMENT NEXT LINE IF RUNNING IN HEROKU SERVER
# import django_heroku
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%l8blyr7l79-&l119umvi$bg0@t_el6w*ktyg=3b-#79-@(^@6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'attendance.apps.AttendanceConfig',
    'bot.apps.BotConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'widget_tweaks',
    # 'django_celery_beat',
    # 'webpack_loader',
    'whitenoise.runserver_nostatic'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'backend.urls'

# FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')
# TEMPLATE_VUE_DIR = os.path.join(FRONTEND_DIR, 'dist')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'attendance_extras': 'attendance.templatetags.attendance_extras',
            }
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# used to access the database
# ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', os.environ['SITEURL']] # UNCOMMENT IF RUNNING IN AZURE 
# ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', 'konken-attendance.herokuapp.com'] # UNCOMMENT IF RUNNING IN HEROKU

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


# UNCOMMENT IF USING HEROKU
# DATABASES = {}
# DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True, default='postgres://qslqyunegixtlx:81cbea16e507a3a57fbfe154baeead09245db520b3334cf8d13faea605d02776@ec2-3-218-112-22.compute-1.amazonaws.com:5432/det79c17hie9ko')

# UNCOMMENT IF USING LOCAL SERVER
DATABASES = {}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'konken',
        'USER': 'postgres',
        'PASSWORD': 'hanachan',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DATABASES = {}
DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True, default='postgres://sampleadmin@sampleforkonken:DBw1nd$g@T3@sampleforkonken.postgres.database.azure.com:5432/attendancebot' )

# UNCOMMENT IF USING IN AZURE
# DATABASES = {}
# DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True, default='postgres://'+os.environ['DBUSER']+'@'+os.environ['DBHOST']+':'+os.environ['DBPASS']+'@'+os.environ['DBHOST']+'.postgres.database.azure.com:5432/'+os.environ['DBNAME'] )

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LINE_CHANNEL_ACCESS_TOKEN = 'QQSuKJEAI4hFp/W99BGPYTWnRSg' \
                            '/zxQSqreky5beDJUWa6dp1K6ALR2rw659aMY02pRZ71wmES6UQGA6Z3EbGtSEZrU1L5UOgzEvORi9D+zV' \
                            '+ZFOxKxkVssnYAQLAvXPKrNzPXfSfRv+RbDKmZ5aEQdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '067566f7f0361fc9cf18e672bc483aad'

LINE_CHANNEL_ACCESS_TOKEN = 'VOVRAnsVX9t4sW2rMqmsRwBosqBIk9RI8aQXn0PBTYoG61AkQjfPx3uVs2EH5zq5Lu+sQ6afUpH679JlT1XALTGvj6SsGXz34HG4AyM9vpJZI4MISK/UcxpU00b0aY1GW3jCgMstlS8m+gLBYvRW2gdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '183aca54f1c2d4ebd9522ecf8cf2db28'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'windsgateheroku@gmail.com'
EMAIL_HOST_PASSWORD = 'obpdkhcfandrgoii'

# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# REDIS_HOST = 'redis://localhost:6379'

# UNCOMMENT TO ALLOW LOGGING IN HEROKU 
# django_heroku.settings(locals(), logging=False)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# SETTINGS RELATED WHEN collectstatic command is executed

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
#location where django collect all static files
# STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
# location where you will store your static files

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# override the User model used for authentication
AUTH_USER_MODEL = 'attendance.User'

# WEBPACK_LOADER = {
#     'DEFAULT': {
#         'BUNDLE_DIR_NAME': 'dist/',
#         'STATS_FILE': os.path.join(BASE_DIR, 'frontend', 'webpack-stats.json')
#     }
# }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

JWT_AUTH = {             
    'JWT_PAYLOAD_HANDLER': 'attendance.handlers.jwt_payload_handler',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=800),
}

# CURRENT_APP_URL = 'konken-attendance.herokuapp.com'
CURRENT_APP_URL = 'konkenapp.azurewebsites.net'
DEFAULT_PASS = "dEf@uLtP@SSF0ReveRy1"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = '/accounts/login/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # HANDLERS #########################################
    'handlers': {
        'console':{
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'file_1':{
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'attendance', 'logs','scanned_cards.log')
        },
    },
    # LOGGERS ##########################################
    'loggers': {
        'general': {
            'handlers': ['console'],
            'level': 'INFO'
        },
        'card_scan':{
            'handlers':['console', 'file_1'],
            'level': 'INFO'
        },
    }

}

"""
    FIXME: When in production, hide the sensitive information eg.:
            > database credentials
            > secret key for encryption
            > default password
            > line channel access tokens
"""