# Generated by Django 3.0.8 on 2020-09-29 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ユーザー名')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID番号')),
                ('line_userid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINEユーザーID番号')),
                ('card_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='カードID')),
                ('line_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='LINEユーザー名')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('first_name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='名かな')),
                ('last_name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓かな')),
                ('year_level', models.SmallIntegerField(blank=True, null=True, verbose_name='学年')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='郵便番号')),
                ('address_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所１')),
                ('address_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所２')),
                ('telephone_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('mobile_num_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='携帯番号１')),
                ('mobile_num_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='携帯番号2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('recipient_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.SmallIntegerField()),
                ('keyword', models.CharField(max_length=300)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PushRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient_user', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='trigger_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trigger', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'user')},
            },
        ),
    ]
