# Generated by Django 3.0.8 on 2020-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_days_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.AlterField(
            model_name='subject',
            name='days',
            field=models.ManyToManyField(to='attendance.WeekDays'),
        ),
    ]
