# Generated by Django 3.0.8 on 2020-10-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20201019_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'user', 'time_in')},
        ),
    ]
