# Generated by Django 3.0.8 on 2020-10-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20201021_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarDays',
        ),
    ]
