# Generated by Django 3.0.8 on 2020-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_calendardays'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='カードID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
