# Generated by Django 3.0.8 on 2020-11-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_cardlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('女', '女'), ('男', '男'), ('なし', 'なし')], default='なし', max_length=3),
        ),
    ]
