# Generated by Django 3.0.8 on 2021-01-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDivision',
            fields=[
                ('level', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='学校区分')),
                ('level_name', models.CharField(max_length=50, verbose_name='学校区分名')),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('year_level', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='学年CD')),
                ('year_level_name1', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年名１')),
                ('year_level_name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年名2')),
                ('year_level_name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年名3')),
                ('level_division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='学年_区分', to='attendance.SchoolDivision')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='学校CD')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名')),
                ('level_division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='学校_区分', to='attendance.SchoolDivision')),
            ],
        ),
    ]
