# Generated by Django 3.0.8 on 2021-01-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_school_schooldivision_yearlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldivision',
            old_name='level',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='schooldivision',
            old_name='level_name',
            new_name='division_name',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='生徒学校', to='attendance.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='生徒学年', to='attendance.YearLevel'),
        ),
    ]
