# Generated by Django 3.0.8 on 2021-02-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20210120_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': '履歴\u3000- Attendance'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name_plural': '祝日 - Holidays'},
        ),
        migrations.AlterModelOptions(
            name='pushrecipients',
            options={'verbose_name_plural': 'Push Recipients'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': '学校\u3000- School'},
        ),
        migrations.AlterModelOptions(
            name='schooldivision',
            options={'verbose_name_plural': '学校区分\u3000- School Division'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'ユーザ - Users'},
        ),
        migrations.AlterModelOptions(
            name='yearlevel',
            options={'verbose_name_plural': '学年\u3000- Year Level'},
        ),
        migrations.AddField(
            model_name='user',
            name='printed_card_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='印刷したカードID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='カードID・シリアルナンバー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='生徒学校', to='attendance.School', verbose_name='生徒学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='生徒学年', to='attendance.YearLevel', verbose_name='生徒学年'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pushrecipients',
            unique_together=set(),
        ),
    ]
