# Generated by Django 3.0.8 on 2021-02-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20210201_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='printed_card_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='印刷したカードID'),
        ),
    ]
