# Generated by Django 3.0.8 on 2021-02-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20210203_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CramSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_channel_access_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Line Channel Access Token')),
                ('line_channel_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='Line Channel Secret')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='塾名')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='塾住所')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='塾slug')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='塾連絡先')),
                ('default_greeting', models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Greeting')),
                ('rich_menu_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '塾 - Cram School',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='cramschool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='学校の塾', to='attendance.CramSchool'),
        ),
        migrations.AddField(
            model_name='user',
            name='cramschool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='生徒の塾', to='attendance.CramSchool'),
        ),
    ]
