# Generated by Django 3.0.8 on 2021-02-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20210215_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cramschool',
            name='default_greeting',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Default Greeting'),
        ),
    ]
