# Generated by Django 3.0.8 on 2021-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20210216_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_userid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='LINEユーザID番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LINEユーザ名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='ユーザ名'),
        ),
    ]
