# Generated by Django 3.0.8 on 2021-02-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20210216_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cramschool',
            name='failed_registration',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Failed Registration Message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cramschool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='塾', to='attendance.CramSchool'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('女', '女'), ('男', '男'), ('なし', 'なし')], default='なし', max_length=3, verbose_name='性別'),
        ),
    ]
