# Generated by Django 3.0.8 on 2021-02-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20210216_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='cramschool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='カード塾', to='attendance.CramSchool'),
        ),
    ]
