# Generated by Django 3.0.8 on 2021-02-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_cardlog_cramschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cramschool',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='塾slug'),
        ),
    ]
