# Generated by Django 3.0.8 on 2021-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20210225_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cramschool',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='塾short name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID番号'),
        ),
    ]
